/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VariasiService } from "../variasi.service";
import { VariasiCreateInput } from "./VariasiCreateInput";
import { Variasi } from "./Variasi";
import { VariasiFindManyArgs } from "./VariasiFindManyArgs";
import { VariasiWhereUniqueInput } from "./VariasiWhereUniqueInput";
import { VariasiUpdateInput } from "./VariasiUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class VariasiControllerBase {
  constructor(protected readonly service: VariasiService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Variasi })
  async createVariasi(
    @common.Body() data: VariasiCreateInput
  ): Promise<Variasi> {
    return await this.service.createVariasi({
      data: data,
      select: {
        createdAt: true,
        gambar: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Variasi] })
  @ApiNestedQuery(VariasiFindManyArgs)
  async variasis(@common.Req() request: Request): Promise<Variasi[]> {
    const args = plainToClass(VariasiFindManyArgs, request.query);
    return this.service.variasis({
      ...args,
      select: {
        createdAt: true,
        gambar: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Variasi })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async variasi(
    @common.Param() params: VariasiWhereUniqueInput
  ): Promise<Variasi | null> {
    const result = await this.service.variasi({
      where: params,
      select: {
        createdAt: true,
        gambar: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Variasi })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVariasi(
    @common.Param() params: VariasiWhereUniqueInput,
    @common.Body() data: VariasiUpdateInput
  ): Promise<Variasi | null> {
    try {
      return await this.service.updateVariasi({
        where: params,
        data: data,
        select: {
          createdAt: true,
          gambar: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Variasi })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVariasi(
    @common.Param() params: VariasiWhereUniqueInput
  ): Promise<Variasi | null> {
    try {
      return await this.service.deleteVariasi({
        where: params,
        select: {
          createdAt: true,
          gambar: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: VariasiWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        itemPrice: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: VariasiWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateVariasi({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: VariasiWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateVariasi({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: VariasiWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateVariasi({
      where: params,
      data,
      select: { id: true },
    });
  }
}
